spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: chartinbox1234@gmail.com
    password: nygltxapwoedhhwr
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

## cookie, 프론트랑 연결할 때엔 주석 해제
server:
  servlet:
    session:
      cookie:
        same-site: none
        secure: true